### card/show
GET http://localhost:80/cards/show/6
Accept: application/json

### uc/relacionadas
GET http://localhost:80/uc/1/related
Accept: application/json

### card/details
GET http://localhost:80/cards/details/1
Accept: aplication/json

### chamar ucs
GET http://localhost:80/uc
Accept: aplication/json